version: '3.8'
services:
  mysql-db:
    # Nombre de contenedor MYSQL
    image: mysql:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mueblesstgo
    ports:
      - 3307:3306
  app:
    container_name: app-migsw-ms
    image: ianrickmers/migsw-ms
    ports:
      - '8081:8081'
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/mueblesstgo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
